drop table t_items if exists;
create table t_items (
    id Long generated by default as identity,
    item_nom varchar(255) not null,
    item_quality integer,
    item_sellin integer,
    primary key (id));

insert into
    t_items (id,item_nom, item_quality, item_sellin)
values
    (1000L,'+5 Dexterity Vest', 20, 12),
    (2000L,'Elixir of the Mongoose', 7, 15),
    (4000L,'Elixir of the Mongoose', 10, 5),
    (3000L,'AgedBrie', 10, 3);